### ISSUE TITLE
VTE Regexp should work with older VTE releases as well

### ISSUE THREAD

**Issue by jest** [gnome-terminator/terminator#10]
Since the commit b2a47a50fdcd867335960d35966dc4cebe4c33c0 the code is broken on Ubuntu 16.04, which uses the old VTE:

```
$ terminator
Traceback (most recent call last):
  File "/usr/bin/terminator", line 122, in <module>
    TERMINATOR.create_layout(OPTIONS.layout)
  File "/usr/share/terminator/terminatorlib/terminator.py", line 311, in create_layout
    window, terminal = self.new_window()
  File "/usr/share/terminator/terminatorlib/terminator.py", line 234, in new_window
    terminal = maker.make('Terminal')
  File "/usr/share/terminator/terminatorlib/factory.py", line 94, in make
    output = func(**kwargs)
  File "/usr/share/terminator/terminatorlib/factory.py", line 106, in make_terminal
    return(terminal.Terminal())
  File "/usr/share/terminator/terminatorlib/terminal.py", line 147, in __init__
    self.update_url_matches()
  File "/usr/share/terminator/terminatorlib/terminal.py", line 273, in update_url_matches
    reg = Vte.Regex.new_for_match(re, len(re), self.regex_flags)
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 139, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.Vte' object has no attribute 'Regex'
```

This is reproducible by using PPA `ppa:gnome-terminator/nightly-gtk3` on 16.04, caused there by commit version `1.91-0~1835~ubuntu16.04.1`.

In https://bugs.launchpad.net/terminator/+bug/1867746/comments/7 you mentioned that the "real" development is moved to GitHub, so I feel encouraged to raise an issue here. :)

(also, I have no idea on how to sanely report the issue on the launchpad...)

Is 16.04 supposed to be dropped? If so, the aformentioned build on LP should be stopped on 1834 for Xenial.

**Comment by lazyfrosch** [comment]
Thanks for your issue

This should have been fixed with #6 and is merged to master, we are working on a release soon.

We don't own the Launchpad project currently, as well as the PPA, so there are no "nightly" builds!

**Comment by lazyfrosch** [comment]
Oh sorry I misread your issue, I will have a look at that!

**Comment by jest** [comment]
@lazyfrosch the released version works on 16.04. However, on 18.04 I have problems:
```

** (terminator:3399): WARNING **: 15:06:11.252: Binding '<Control><Alt>a' failed!
Unable to bind hide_window key, another instance/window has it.
Traceback (most recent call last):
  File "./terminator", line 123, in <module>
    TERMINATOR.create_layout(OPTIONS.layout)
  File "/home/jest/Desktop/terminator-1.92/terminatorlib/terminator.py", line 310, in create_layout
    window, terminal = self.new_window()
  File "/home/jest/Desktop/terminator-1.92/terminatorlib/terminator.py", line 233, in new_window
    terminal = maker.make('Terminal')
  File "/home/jest/Desktop/terminator-1.92/terminatorlib/factory.py", line 93, in make
    output = func(**kwargs)
  File "/home/jest/Desktop/terminator-1.92/terminatorlib/factory.py", line 105, in make_terminal
    return(terminal.Terminal())
  File "/home/jest/Desktop/terminator-1.92/terminatorlib/terminal.py", line 160, in __init__
    self.update_url_matches()
  File "/home/jest/Desktop/terminator-1.92/terminatorlib/terminal.py", line 295, in update_url_matches
    self._add_regex('full_uri', re)
  File "/home/jest/Desktop/terminator-1.92/terminatorlib/terminal.py", line 272, in _add_regex
    reg = Vte.Regex.new_for_match(re, len(re), self.regex_flags)
GLib.Error: vte-regex-error: PCRE2 not supported (2147483647)
```

I run the program with `.\terminator` from the released 1.92 version.

**Comment by jest** [comment]
Searching more on this shows that Ubuntu has patched VTE to not use pcre2 lib. At least in 17.10 and 18.04. (Probably fixed in 19.04, but don't have a system to test this ATM).

Looks like `PCRE2_MULTILINE` is required for proper links highlighting, so I have no idea how to fix this. :(

**Comment by dgutov** [comment]
> Probably fixed in 19.04, but don't have a system to test this ATM

It works on 19.10, FWIW.

**Comment by lazyfrosch** [comment]
So they use the modern functions, but bail on the PCRE constant for flags (or better the byte value).

Amazing...

**Comment by lazyfrosch** [comment]
Further fixes in #28
