### ISSUE TITLE
drag and drop of path stopped working in terminator version 2.1.3

### ISSUE THREAD

**Issue by pvdam3** [gnome-terminator/terminator#742]
**Describe the bug**
Since the update to v 2.1.3, dragging and dropping of files and directories in order to directly paste the path in the terminal stopped working. I checked v2.1.2 and v2.1.1 and in both cases, this functionality was still there. This functionality was added in v2.1.0 (https://github.com/gnome-terminator/terminator/issues/159).

**To Reproduce**
Steps to reproduce the behavior: select a file or folder and drag it into the terminal window

**Expected behavior**
the shell should paste `'/home/peter/Downloads'`

**Desktop (please complete the following information):**
 - OS or Linux Distribution: ubuntu 20.04
 - Version 20.04
 - Display Technology: X11

**Additional context**
When running terminator from a ubuntu terminal, I see the following error message appearing:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/terminatorlib/terminal.py", line 1264, in on_drag_data_received
    term.feed(txt.encode())
  File "/usr/lib/python3/dist-packages/terminatorlib/terminal.py", line 1697, in feed
    self.vte.feed_child(text.encode())
AttributeError: 'bytes' object has no attribute 'encode'
```

N.B. thanks for your great work!

**Comment by mattrose** [comment]
dupe of #727 and fixed with #728 but not released yet (as of 2.1.3)
